### ISSUE TITLE
Filter on Menu

### ISSUE THREAD

**Issue by cseickel** [MunifTanjim/nui.nvim#106]
What do you think about adding a search as you type filter to the Menu class, similar to fzf or Telescope? I wouldn't mind working on it if you like the idea but don't want to do it yourself.

**Comment by MunifTanjim** [comment]
Would it be just a combination of multiple components? If that's the case, then we should actually focus on:

- https://github.com/MunifTanjim/nui.nvim/issues/18

I couldn't manage the time to look into it yet. So if you have any ideas about how multiple windows can be easily arranged to create complex layouts like fzf or Telescope, it would be a great help! 😄

But I would discourage to just have a component that looks like fzf or Telescope. The idea is to give plugin authors something that they can mix and match and build upon.

**Comment by cseickel** [comment]
Hmm... It may be possible to hack the prompt functionality instead, but stacking windows is the traditional way of doing it. This functionality could just be demonstrated as an example in the wiki if you don't want to include it in the Menu implementation.

I think I will hop over to #18 and at least start a discussion, it would be nice to have that generic flexbox/grid style layout functionality.

**Comment by cseickel** [comment]
> > It may be possible to hack the prompt functionality instead
> 
> I don't think I'm familar with that trick. Can you please share an example? 🤔

It' just an idea at the moment. I'm thinking about trying to use a `prompt-buffer` to provide the input at the bottom of the window, and then hacking in a way to react to each key-press instead of waiting for a final submit on enter. I might try it out later, and if I do I'll let you know if it works. I'd like to us this for the filtering in neo-tree rather than the floating window I have now.

**Comment by cseickel** [comment]
> I'm thinking about trying to use a prompt-buffer to provide the input at the bottom of the window, and then hacking in a way to react to each key-press instead of waiting for a final submit on enter. 

Just to follow up on that one, I tried it and it did not work well. I think it would be easier to execute that idea with a normal buffer where you prevent input on any line other than the chosen "prompt" section.

> But I would discourage to just have a component that looks like fzf or Telescope. The idea is to give plugin authors something that they can mix and match and build upon.

Let me just explain the use case. While telescope and fzf are good at filtering simple lists of things in a very generic way, I would prefer to display those items in a very specific way using the configs, highlight groups, events, etc that are a part of my plugin. I would not want to use the picker or sorter from those other plugins which don't fit with the look and feel of my plugin. Building a list of Text objects in Nui is so much easier than trying to format the list in telescope or fzf.

I also don't want to take a dependency on one of these other plugins just to filter a single list.

If you disagree, i won't be offended if you close the issue. Maybe this is something better as an example in the Wiki.

**Comment by MunifTanjim** [comment]
Oh no, I completely understand your usecase. Let me share my thoughts so that it's a bit clear what I meant when I said:

> But I would discourage to just have a component that looks like fzf or Telescope. 

So, this usecase needs the following things:

- A input box where you can type and do something with the value as it changes (`nui.input` and `on_change` callback)
- A buffer where you can show a list of items and get the currently focused item (`nui.tree` and `get_node`, `set_nodes` methods)
- A buffer where you can show some content for the currently focused item from `nui.tree`

That's the basic idea. But when you start to do that you'll notice that arranging the UI components is just part of the problem, you'll need some more things to make it work (e.g.: you'll want to do the filtering in a non-blocking way using Lua co-routines etc.).

And https://github.com/MunifTanjim/nui.nvim/issues/18 is exactly for solving the "arranging UI components" problem.

But I don't think `nui.nvim` should be concerned about the other part of the problem.

What I instead want to do is to provide the APIs (missing functionalities or methods) that are lacking in the existing components so that the whole thing can be made. For example: last time when we talked about `nui.tree`, it was lacking some things that are now available:

- `parent_node` is passed to `prepare_node` (https://github.com/MunifTanjim/nui.nvim/blob/6f803e88/lua/nui/tree/init.lua#L340). This is needed for rendering the indent lines (blue lines in the screenshot) for a tree structure, i.e. you need to know if a specific node is the last child of the parent node.

    <img width="169" alt="image" src="https://user-images.githubusercontent.com/8050659/154987368-d4a34b37-c771-4c2f-8f82-3526f42fcd09.png">

- The `linenr` is returned from `get_node` (https://github.com/MunifTanjim/nui.nvim/blob/6f803e88/lua/nui/tree/init.lua#L221). Sometimes you need to know the line number on which a specific node is currently rendered, this is needed for that.

Let me know if you have some more questions around this, I'm happy to answer.

**Comment by cseickel** [comment]
This makes sense. I really already did all this work for the tree filtering, but what brought me here was the idea of showing a menu for available commands (mappings) in the window, rather than filtering the tree itself. 

When I saw the Menu component I hoped I could just drop that in and get the filtering logic for free, because it can get a bit involved when you take into account navigating and selecting items in the main window while the focus remains on the input window. One thing that could help with that is to add methods to the Popup that allow moving the cursor position without focusing the window. Then it would at least be able to bind some keys from the input window that would allow you to use Up/Down/Enter to make your selection.

**Comment by MunifTanjim** [comment]
> One thing that could help with that is to add methods to the Popup that allow moving the cursor position without focusing the window.

I'm a bit confused here... Isn't it doable with just `vim.api.nvim_win_set_cursor(popup.winid, { linenr, col })`? 🤔

Maybe I'm missing something?

**Comment by cseickel** [comment]
> > One thing that could help with that is to add methods to the Popup that allow moving the cursor position without focusing the window.
> 
> I'm a bit confused here... Isn't it doable with just `vim.api.nvim_win_set_cursor(popup.winid, { linenr, col })`? 🤔
> 
> Maybe I'm missing something?

For the most part, yes I guess you are right. A lot of my own complication comes from code to find a line by the node id. What remains is just code to:
- move the cursor in a relative manner up or down from the current line, which needs to take into account whether you are currently at the first or last line in the target buffer.
- scroll the window appropriately when the cursor changes

... and the scrolling logic is particular to my own use case so probably not appropriate for a generic library at all. 

Honestly, I think the end result here is that nothing really needs to be added! I'm sorry for wasting your time on this, but thank you for indulging me!

**Comment by MunifTanjim** [comment]
> A lot of my own complication comes from code to find a line by the node id

Did you try the new `local node, linenr = tree:get_node(id?)` ? That should cut down some codes.

---

I'm not exactly sure what `bottom_scroll_padding` does, is it comparable to `'scrolloff'` window option?

**Comment by cseickel** [comment]
> Did you try the new `local node, linenr = tree:get_node(id?)` ? That should cut down some codes.

I didn't know that existed! I will definitely start using it now, thanks!

> I'm not exactly sure what `bottom_scroll_padding` does, is it comparable to `'scrolloff'` window option?

Basically. The reason for this is that when I am filtering a non-floating window, I have to float the input above the split window at the bottom, which will cover the last three lines of the window. The `bottom_scroll_padding` treats the window as being that much smaller when calculating scroll position to ensure that the cursor is never under that floating input. The difference between this and just setting a `scrolloff` is that this scrolls the window past the last line if needed.

If we are able to make #18 work well for non-floating split windows, I will drop that floating input in favor of a one line split window and simplify the code.
