### ISSUE TITLE
[BUG] Popup not properly closed

### ISSUE THREAD

**Issue by vuki656** [MunifTanjim/nui.nvim#29]
Code used:

```lua
M.pop = function()
    local Popup = require("nui.popup")

    local popup = Popup({
        focusable = true,
        enter = true,
        border = {
            style = "rounded",
            highlight = "Normal",
            text = {
                top = "I am a title",
                top_align = "left",
            },
        },
        position = "50%",
        size = {
            width = "80%",
            height = "60%",
        },
    })

    popup:mount()
end
```

Result:
![Peek 2021-08-13 20-53](https://user-images.githubusercontent.com/8104698/129405845-46b66541-38ec-41dc-9d54-305a34db196e.gif)

**Comment by MunifTanjim** [comment]
This one was by design. `Popup` is a general purpose component and different use-cases might have different requirements about when a popup is supposed to be closed and perform cleanup. So you'll need to call `popup:unmount()` to do the cleanup (various keymap and autocmd functions) and close the buffers and windows for the popup and its border.

You can call unmount when the popup buffer is closed by doing something like this:

```lua
  local event = require("nui.utils.autocmd").event

  popup:on(event.BufHidden, function()
    vim.schedule(function()
      popup:unmount()
    end)
  end)
```

**Comment by vuki656** [comment]
Ohh, okay.
