### ISSUE TITLE
Contents of a buffer appear after the buffer appears for a while

### ISSUE THREAD

**Issue by vollowx** [MunifTanjim/nui.nvim#334]
**Ref**

- [nvim-neo-tree](https://github.com/nvim-neo-tree/neo-tree.nvim)
- - The buffer for the file explorer appear firstly, after a while the file tree appears
- [noice.nvim](https://github.com/folke/noice.nvim)
- - The cmdline popup firstly appears, the icon then appears
- - The hover window of LSP firstly appears, the contents then appears

I don't know if this's the right behavior, but the default LSP hover window just comes with content, and this really annoys me.

**Comment by MunifTanjim** [comment]
It's not an issue with `nui.nvim`. You should report this to those projects.

**Comment by pysan3** [comment]
For the case of neo-tree, that is purposely done to stop flickering when you switch from one source to another. (`<`, `>` keybind).

https://private-user-images.githubusercontent.com/14960414/218556272-809e5ba1-6985-4d37-a663-4bcb62ed46cf.mp4

The window must be shared between sources, and guarantee that a window is there before start rendering the content.

Could you explain why this behavior _really annoys you_? @vollowx 

IMO this is much better and most software use this method in an async context.
Like when you press a link in the browser, you jump to a blank page and see the page gradually load incrementally. Or otherwise you will have to wait until everything in the page is rendered completely which is very bad UX.

**Comment by vollowx** [comment]
I mean opening the neo-tree window, not switching sources.

As the rendering is fast enough, is it necessary to delay the rendering? I'm not sure about this and just get used to the just-in-time rendering of NeoVim e.g. LSP hover and some other plugins e.g. nvim-tree.
