### ISSUE TITLE
Backspace doesn't work after leaving normal mode in an input

### ISSUE THREAD

**Issue by VonHeikemen** [MunifTanjim/nui.nvim#48]
(I know this is a bug in neovim. Because of `buftype=prompt`)

If one enters normal mode and edits the text, then goes back to insert mode `backspace` doesn't work as expected. The remaining text can't be deleted with backspace.

There is a [workaround](https://github.com/neovim/neovim/issues/14116#issuecomment-977555102) for this.

```lua
function PromptBackspace()
  -- Have to know the length of the prompt
  local prompt_length = 2
  local cursor = vim.api.nvim_win_get_cursor(0)
  local line = cursor[1]
  local col = cursor[2]

  if col ~= prompt_length then
    vim.api.nvim_buf_set_text(0, line - 1, col - 1, line - 1, col, {''})
    vim.api.nvim_win_set_cursor(0, {line, col - 1})
  end
end
```

It seems this function works fine when bound to backspace (`<BS>`) in insert mode.

**Comment by MunifTanjim** [comment]
Hey @VonHeikemen, thanks for sharing this workaround! 😃

For the bug, I think there's a upstream PR open for it? 🤔
 
- https://github.com/neovim/neovim/pull/15881

We should probably wait for that to be merged.

In the meantime, let's keep this issue open so that others can easily find the workaround.
